from pathlib import Path
from typing import Any, Callable

from ase import Atoms
from wfl.autoparallelize.remoteinfo import RemoteInfo

from alomancy.utils.remote_job_executor import RemoteJobExecutor


def remote_atoms_list_submitter(
    remote_info: RemoteInfo,
    base_name: str,
    specific_job_dict: dict[str, Any],
    target_file: str,
    input_atoms_list: list[Atoms],
    function: Callable | None = None,
    function_kwargs: dict[str, Any] | None = None,
    verbose: int = 0,
) -> list[str]:
    """
    A generic function to submit a list of Atoms objects to a remote job executor with an arbitrary function.

    Parameters
    ----------
    remote_info : RemoteInfo
        Information about the remote job execution environment.
    base_name : str
        Base name for the output directory.
    specific_job_dict : dict[str, Any]
        Dictionary containing specific job settings.
    target_file : str
        Name of the target file to be generated by the function.
    input_atoms_list : list[Atoms]
        List of Atoms objects to be processed.
    function : Callable, optional
        Function to be executed remotely, by default None.
    function_kwargs : dict[str, Any], optional
        Additional keyword arguments for the function, by default None.
    verbose : int, optional
        Verbosity level, by default 0.

    Returns
    -------
    list[str]
        List of paths to the generated target files.
    """

    workdir = Path("results", base_name)
    job_dir = Path(workdir, specific_job_dict["name"])

    def find_target_files():
        return list(
            Path.glob(job_dir, f"{specific_job_dict['name']}_output_*/{target_file}")
        )

    target_file_list = find_target_files()

    if len(target_file_list) >= len(input_atoms_list) and verbose > 0:
        print(
            f"All {len(input_atoms_list)} {specific_job_dict['name']} runs finished. Skipping submission."
        )
        return target_file_list

    elif len(target_file_list) != 0 and verbose > 0:
        print(
            f"Found {len(target_file_list)} existing {specific_job_dict['name']} runs. Reusing them."
        )
        input_atoms_list = input_atoms_list[len(target_file_list) :]

    executor = RemoteJobExecutor(remote_info)

    job_configs = [
        {
            "function_kwargs": {
                "input_structure": input_atoms_list[i],
                "out_dir": str(
                    Path(f"{job_dir}/{specific_job_dict['name']}_output_{i}")
                ),
                **function_kwargs,
            }
        }
        for i in range(len(input_atoms_list))
    ]

    executor.run_and_wait(
        function=function,
        job_configs=job_configs,
        common_output_pattern=str(
            Path(job_dir, f"{specific_job_dict['name']}_output_{{job_id}}")
        ),
    )

    return find_target_files()
